sudo: required
services:
  - docker

before_install:
  - docker build -t chamika/fib-app -f ./client/Dockerfile.dev ./client

# This -- --coverage commans let`s docker to exit with 0 signal, otherwise travis
# will asume test does not passed within the time limit. So it failes the build.
script:
  - docker run chamika/fib-app npm test -- --coverage

after_success:
  - docker build -t chamika/multi-client ./client
  - docker build -t chamika/multi-server ./server
  - docker build -t chamika/multi-worker ./worker
  - docker build -t chamika/multi-nginx ./nginx
  # Log into Docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and pushed them to docker hub.
  - docker push chamika/multi-client
  - docker push chamika/multi-server
  - docker push chamika/multi-worker
  - docker push chamika/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: fib-app
  env: FibApp-env
  bucket_name: elasticbeanstalk-ap-southeast-1-892586227525
  bucket_path: docker_multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY



  